---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view
  namespace: test-ns
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "describe"]
  - apiGroups: [ "apps" ]
    resources: [ "pods", "pods/log" ]
    verbs: [ "get", "list", "describe"]
