---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dep
  namespace: prod-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
      - image: anutkafluff/13-1kubernetes-config_backend:latest
        name: back-app
        ports:
        - containerPort: 9000
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@postgres-service:5432/news

