all:
  hosts:
    cp1:
      ansible_host: 51.250.29.0
      ip: 10.129.0.33
      ansible_user: anna
    node1:
      ansible_host: 84.252.143.68
      ip: 10.129.0.6
      ansible_user: anna
    node2:
      ansible_host: 51.250.110.181
      ip: 10.129.0.17
      ansible_user: anna
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
