---
all:
  hosts:
    vm-1:
      ansible_host: 51.250.21.24
    vm-2:
      ansible_host: 51.250.109.224
  children:
    sonarqube:
      hosts:
        vm-1:
    nexus:
      hosts:
        vm-2:
    postgres:
      hosts:
        vm-1:
  vars:
    ansible_connection: ssh
    ansible_user: anna
