---
apiVersion: v1
kind: Service
metadata:
  name: back-service
  namespace: prod-ns
spec:
  type: ClusterIP
  selector:
    app: back-app
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
