---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-dep
  namespace: prod-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - image: anutkafluff/13-1-kubernetes-config_frontend:latest
        name: front-app
        ports:
        - containerPort: 80
        env:
          - name: BASE_URL
            value: http://back:9000
