---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hello-world-policy
  namespace: test-ns
spec:
  podSelector:
    matchLabels:
      app: hello-world
  ingress:
  - {}
  policyTypes:
  - Ingress
